### ISSUE TITLE
CastError: Cast to ObjectId failed for value "system" at path "_id" for model "Report"

### ISSUE THREAD

**Issue by UtopiaBeam** [2110423-2019-2/sec1_Numja-Back-End-#13]
In PR #10 , there is a fatal bug which no one know why and how to fix it yet.

This happened when GET system reports.

```
numja-backend | CastError: Cast to ObjectId failed for value "system" at path "_id" for model "Report"
numja-backend |     at new CastError (/server/node_modules/mongoose/lib/error/cast.js:39:11)
numja-backend |     at ObjectId.cast (/server/node_modules/mongoose/lib/schema/objectid.js:246:11)
numja-backend |     at ObjectId.SchemaType.applySetters (/server/node_modules/mongoose/lib/schematype.js:975:12)
numja-backend |     at ObjectId.SchemaType._castForQuery (/server/node_modules/mongoose/lib/schematype.js:1389:15)
numja-backend |     at ObjectId.SchemaType.castForQuery (/server/node_modules/mongoose/lib/schematype.js:1379:15)
numja-backend |     at ObjectId.SchemaType.castForQueryWrapper (/server/node_modules/mongoose/lib/schematype.js:1358:15)
numja-backend |     at cast (/server/node_modules/mongoose/lib/cast.js:315:32)
numja-backend |     at model.Query.Query.cast (/server/node_modules/mongoose/lib/query.js:4683:12)
numja-backend |     at model.Query.Query._castConditions (/server/node_modules/mongoose/lib/query.js:1861:10)
numja-backend |     at model.Query.<anonymous> (/server/node_modules/mongoose/lib/query.js:2116:8)
numja-backend |     at model.Query._wrappedThunk [as _findOne] (/server/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
numja-backend |     at process.nextTick (/server/node_modules/kareem/index.js:369:33)
numja-backend |     at process._tickCallback (internal/process/next_tick.js:61:11)
```

Similar thing happened when GET user reports.

**Comment by UtopiaBeam** [comment]
Previous cause assumptions:
- **`find()` with conditions**. However, this did not happen when test in User module.
- **`ReportType` enum**. But got same error when change to `string` type.
- **`reporter` and `reportedUser` fields**. Same as above.

**Comment by UtopiaBeam** [comment]
The cause is `/report/:id` is defined before `/report/system` and `/report/user` so it tries to parse `system` and `user` to `:id`. Fixed.
